[crowsnest]
log_path: /home/klipper/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false

[cam 1]
mode: ustreamer
port: 8080
device: /dev/v4l/by-id/usb-046d_C922_Pro_Stream_Webcam_D2D4BCDF-video-index0
resolution: 1920x1080
max_fps: 30
v4l2ctl: focus_automatic_continuous=0,focus_absolute=30,white_balance_automatic=0,white_balance_temperature=4500,saturation=128,contrast=128