[crowsnest]
log_path: /home/klipper/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false

[cam 1]
mode: ustreamer
port: 8080
device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:5.1:1.0-video-index0
resolution: 1280x720
max_fps: 15
v4l2ctl: brightness=128,contrast=32,saturation=64,sharpness=24,gain=0,white_balance_automatic=1,exposure_auto=3,exposure_auto_priority=1,focus_automatic_continuous=1,zoom_absolute=100,pan_absolute=0,tilt_absolute=0